name: SundialKit
settings:
  LINT_MODE: ${LINT_MODE}
packages:
  SundialKit:
    path: .
  SundialKitBinary:
    path: Packages/SundialKitBinary
  SundialKitCombine:
    path: Packages/SundialKitCombine
  SundialKitMessagable:
    path: Packages/SundialKitMessagable
  SundialKitStream:
    path: Packages/SundialKitStream
aggregateTargets:
  Lint:
    buildScripts:
      - path: Scripts/lint-all.sh
        name: Lint
        basedOnDependencyAnalysis: false
    schemes: {}
