name: Sundial

options:
  bundleIdPrefix: com.brightdigit.sundial
  deploymentTarget:
    iOS: "16.0"
    watchOS: "9.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.1"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}

# Reference the local Swift Package
packages:
  Sundial:
    path: .

targets:
  # MARK: - Combine iOS App

  SundialCombine-iOS:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "16.0"
    sources:
      - path: Apps/SundialCombine
      - path: Resources/iOS
        type: folder
        buildPhase: resources
    dependencies:
      - package: Sundial
        product: SundialDemoCombine
      - target: SundialCombine-watchOS
        embed: true
    info:
      path: Resources/iOS/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_NAME: SundialCombine
        PRODUCT_BUNDLE_IDENTIFIER: com.brightdigit.sundial.combine.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_EXPERIMENTAL_FEATURE: StrictConcurrency
        ENABLE_UPCOMING_FEATURE: ExistentialAny
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO

  # MARK: - Combine watchOS App

  SundialCombine-watchOS:
    type: application
    platform: watchOS
    deploymentTarget:
      watchOS: "9.0"
    sources:
      - path: Apps/SundialCombine
      - path: Resources/watchOS
        type: folder
        buildPhase: resources
    dependencies:
      - package: Sundial
        product: SundialDemoCombine
    info:
      path: Resources/watchOS/Info-Combine.plist
      properties:
        WKApplication: true
        WKCompanionAppBundleIdentifier: com.brightdigit.sundial.combine.ios
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
    settings:
      base:
        PRODUCT_NAME: SundialCombine
        PRODUCT_BUNDLE_IDENTIFIER: com.brightdigit.sundial.combine.ios.watchkitapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_EXPERIMENTAL_FEATURE: StrictConcurrency
        ENABLE_UPCOMING_FEATURE: ExistentialAny
        TARGETED_DEVICE_FAMILY: "4"
        SDKROOT: watchos

  # MARK: - Stream iOS App

  SundialStream-iOS:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "16.0"
    sources:
      - path: Apps/SundialStream
      - path: Resources/iOS
        type: folder
        buildPhase: resources
    dependencies:
      - package: Sundial
        product: SundialDemoStream
      - target: SundialStream-watchOS
        embed: true
    info:
      path: Resources/iOS/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_NAME: SundialStream
        PRODUCT_BUNDLE_IDENTIFIER: com.brightdigit.sundial.stream.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_EXPERIMENTAL_FEATURE: StrictConcurrency
        ENABLE_UPCOMING_FEATURE: ExistentialAny
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO

  # MARK: - Stream watchOS App

  SundialStream-watchOS:
    type: application
    platform: watchOS
    deploymentTarget:
      watchOS: "9.0"
    sources:
      - path: Apps/SundialStream
      - path: Resources/watchOS
        type: folder
        buildPhase: resources
    dependencies:
      - package: Sundial
        product: SundialDemoStream
    info:
      path: Resources/watchOS/Info-Stream.plist
      properties:
        WKApplication: true
        WKCompanionAppBundleIdentifier: com.brightdigit.sundial.stream.ios
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
    settings:
      base:
        PRODUCT_NAME: SundialStream
        PRODUCT_BUNDLE_IDENTIFIER: com.brightdigit.sundial.stream.ios.watchkitapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_EXPERIMENTAL_FEATURE: StrictConcurrency
        ENABLE_UPCOMING_FEATURE: ExistentialAny
        TARGETED_DEVICE_FAMILY: "4"
        SDKROOT: watchos

schemes:
  SundialCombine:
    build:
      targets:
        SundialCombine-iOS: all
        SundialCombine-watchOS: all
    run:
      config: Debug
    archive:
      config: Release

  SundialStream:
    build:
      targets:
        SundialStream-iOS: all
        SundialStream-watchOS: all
    run:
      config: Debug
    archive:
      config: Release
